"""empty message

Revision ID: 13b464e9c01c
Revises: 80570872caf4
Create Date: 2018-05-05 13:02:16.832560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13b464e9c01c'
down_revision = '80570872caf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('top_1', sa.String(length=300), nullable=True))
    op.add_column('products', sa.Column('top_2', sa.String(length=300), nullable=True))
    op.add_column('products', sa.Column('top_3', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'top_3')
    op.drop_column('products', 'top_2')
    op.drop_column('products', 'top_1')
    # ### end Alembic commands ###
