"""empty message

Revision ID: 80570872caf4
Revises: b4ab7a26e758
Create Date: 2018-04-25 22:41:53.895893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80570872caf4'
down_revision = 'b4ab7a26e758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('similar_products',
    sa.Column('id', sa.String(length=300), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=600), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('similar_products')
    # ### end Alembic commands ###
