"""empty message

Revision ID: bdf99762482b
Revises: 43e836839f87
Create Date: 2018-03-29 12:46:45.283275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdf99762482b'
down_revision = '43e836839f87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
